# Verification

In [1]:
import pandas as pd
from compare import compare

In [2]:
df1 = pd.read_csv('../data/sample500_bundesliga2.csv')
df2 = pd.read_csv('../fetch/out/Germany_2_Bundesliga__2025_2026.csv')

In [3]:
SORT_BY = ["Market value", "Team within selected timeframe", "Team", "Player"]

def order(df):
    d = df.copy()
    d["_mv"] = pd.to_numeric(d["Market value"], errors="coerce")   # handles int or "€10M"
    d = d.sort_values(
        ["_mv", "Team within selected timeframe", "Team", "Player"],
        ascending=[False, True, True, True],   # market value high→low, rest A→Z
        na_position="last",
        kind="mergesort",                      # stable
    ).drop(columns="_mv").reset_index(drop=True)
    return d

In [4]:
df1 = order(df1)
df2 = order(df2)

In [5]:
df1.head()

,Player,Team,Team within selected timeframe,Position,Age,Market value,Contract expires,Matches played,Minutes played,Goals,...,Prevented goals per 90,Back passes received as GK per 90,Exits per 90,Aerial duels per 90.1,Free kicks per 90,Direct free kicks per 90,"Direct free kicks on target, %",Corners per 90,Penalties taken,"Penalty conversion, %"
0,M. Berisha,Kaiserslautern,Kaiserslautern,CF,28,10000000,2027-06-30,11,683,2,...,NaN,0.00,NaN,NaN,0.00,0.00,0.0,0.0,0,0.0
1,M. Ljubičić,Union Berlin,Fortuna Düsseldorf,"CF, LAMF",24,8000000,NaN,10,696,0,...,NaN,0.52,NaN,NaN,0.00,0.00,0.0,0.0,0,0.0
2,E. Mašović,NaN,Bochum,"RCB, CB",27,5000000,NaN,13,901,0,...,NaN,2.00,NaN,NaN,0.00,0.00,0.0,0.0,0,0.0
3,P. Klemens,Hertha BSC,Hertha BSC,"RDMF, CB, RCMF",21,5000000,2028-06-30,7,399,1,...,NaN,1.58,NaN,NaN,0.00,0.00,0.0,0.0,0,0.0
4,F. Reese,Wolfsburg,Hertha BSC,"LAMF, RAMF, CF",28,5000000,2030-06-30,33,3089,10,...,NaN,0.12,NaN,NaN,0.15,0.15,0.0,0.0,5,80.0

In [6]:
df2.head()

,Player,Team,Team within selected timeframe,Position,Age,Market value,Contract expires,Matches played,Minutes played,Goals,...,Prevented goals per 90,Back passes received as GK per 90,Exits per 90,Aerial duels per 90.1,Free kicks per 90,Direct free kicks per 90,"Direct free kicks on target, %",Corners per 90,Penalties taken,"Penalty conversion, %"
0,M. Berisha,Kaiserslautern,Kaiserslautern,CF,28,10000000,2027-06-30,11,683,2,...,NaN,0.00,NaN,NaN,0.00,0.00,0.0,0.0,0,0.0
1,M. Ljubičić,Union Berlin,Fortuna Düsseldorf,"CF, LAMF",24,8000000,NaN,10,696,0,...,NaN,0.52,NaN,NaN,0.00,0.00,0.0,0.0,0,0.0
2,E. Mašović,NaN,Bochum,"RCB, CB",27,5000000,NaN,13,901,0,...,NaN,2.00,NaN,NaN,0.00,0.00,0.0,0.0,0,0.0
3,P. Klemens,Hertha BSC,Hertha BSC,"RDMF, CB, RCMF",21,5000000,2028-06-30,7,399,1,...,NaN,1.58,NaN,NaN,0.00,0.00,0.0,0.0,0,0.0
4,F. Reese,Wolfsburg,Hertha BSC,"LAMF, RAMF, CF",28,5000000,2030-06-30,33,3089,10,...,NaN,0.12,NaN,NaN,0.15,0.15,0.0,0.0,5,80.0

This will:

1. build a Key column (Player | Team | Age) inside df1
2. build the same inside df2
3. compare every cell, matched by that key, to check for differences

In [7]:
compare(df1, df2, key=None)

======================================================================
COMPARISON REPORT
======================================================================
generated : 2026-08-12 15:56:22
df1       : 538 rows x 115 columns
df2       : 538 rows x 115 columns
mode      : POSITIONAL (row i vs row i)

----------------------------------------------------------------------
SHAPE
----------------------------------------------------------------------
rows        : df1=538  df2=538   OK
columns     : df1=115  df2=115   OK
column names: identical & same order

----------------------------------------------------------------------
CELL VALUES  (row i vs row i, no key)
----------------------------------------------------------------------

PASS  538 rows, 61870 cells, 0 different

======================================================================
SUMMARY
======================================================================
  row count      PASS
  column count   PASS
  column names   PASS
  cell values    PASS

RESULT: IDENTICAL
======================================================================

written to C:\Users\hasht\Desktop\Cloned Repositories\hidden-gems\devkit\comparison_report.txt

True